# Top of Podfile
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# Add this if missing
source 'https://cdn.cocoapods.org/'

platform :ios, '13.0' # or your min version
prepare_react_native_project!

target 'EdgeLLM' do
  config = use_native_modules!

  # Explicit audio recorder configuration
  pod 'react-native-audio-recorder-player',
    :path => '../node_modules/react-native-audio-recorder-player',
    :podspec => '../node_modules/react-native-audio-recorder-player/AudioRecorderPlayer.podspec'

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  # Workaround for Xcode 14+
  post_install do |installer|
    react_native_post_install(installer)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end